hljs_theme:
  description: "Select the theme you want code blocks to use. You can visit <a target='_blank' href='https://highlightjs.org/static/demo/'>the hljs demo page</a> to preview the themes"
  default: base16-windows-95
  type: enum
  choices:
    - base16-windows-95
hljs_dark_match:
  default: true
  description: "Load dark color scheme if available"
